name: Lash Out
favicon: null
layout_spectrum: 0.88001
typography_spectrum: 0.61616
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b09a75'
    - '#846d4b'
    - '#4e3813'
    - '#fce6c1'
    - '#2b1500'
  brandStrength: 0.3665928295813501
  lightness: 0.5625
  saturation: 0.5519022140651941
  rhythmicContrast: 0.75
purpose: []
